# Generated by Django 6.0.1 on 2026-03-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_blacklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blacklistedtoken',
            options={'verbose_name': 'Blacklisted Token', 'verbose_name_plural': 'Blacklisted Tokens'},
        ),
        migrations.AlterModelOptions(
            name='outstandingtoken',
            options={'ordering': ('user',), 'verbose_name': 'Outstanding Token', 'verbose_name_plural': 'Outstanding Tokens'},
        ),
    ]
