# Generated by Django 6.0.1 on 2026-03-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_blacklist', '0002_alter_blacklistedtoken_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistedtoken',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='outstandingtoken',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
