# Generated by Django 6.0.1 on 2026-03-17 18:08

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=100)),
                ('cover_url', models.URLField(max_length=500)),
                ('audio_url', models.URLField(blank=True, max_length=500, null=True)),
                ('duration', models.CharField(max_length=10)),
                ('mood', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'songs',
                'ordering': ['-created_at'],
            },
        ),
    ]
