# Generated by Django 6.0.1 on 2026-03-18 18:53

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_song_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='embedding',
            field=django_mongodb_backend.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=384),
        ),
    ]
